current_session = {
    "session": {
        "session_id": None,
        "kickboard_id": None,
        "user_id": None,
        "active": False,
    },
    "sensor": {
        "face_score": 0.92,
        "helmet_verified": False,
        "helmet_score": 0.0,
        "weight": 65.3,
        "gas": 0.12,
        "mq3_baseline": None,
        "baseline_status": "measuring",
        "blow_status": "ready",
        "blow_duration": 0.0,
        "blow_required_seconds": 1.0,
        "blow_progress": 0.0,
        "hw484_blow_detected": False,
    },
    "warning": {
        "count": 0,
        "reasons": [],
        "current_reason": None,
        "is_two_person": False,
        "is_drunk": False,
    },
    "device": {
        "is_locked": True,
        "status": "waiting",
        "stm32_connected": False,
        "safety_state": "starting",
    },
}
